// different types of javascript keywords

let keywords = {
  "Vanilla Js": [
    "let",
    "break",
    "case",
    "catch",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "for",
    "function",
    "if",
    "in",
    "new",
    "return",
    "switch",
    "this",
    "throw",
    "try",
    "typeof",
    "let",
    "while",
    "class",
    "const",
    "enum",
    "export",
    "extends",
    "import",
    "super",
    "static",
    "yield",
    "null",
    "true",
    "false",
    "undefined",
    "boolean",
  ],
  DOM: [
    "document",
    "getElementById",
    "getElementsByClassName",
    "getElementsByName",
    "querySelector",
    "querySelectorAll",
    "append",
    "appendChild",
    "remove",
    "removeItem",
    "removeChild",
    "removeEventListener",
    "removeAttribute",
    "window",
    "event",
    "addEventListener",
    "node",
    "click",
    "keydown",
    "keyup",
    "keypress",
    "mouseenter",
    "mouseleave",
    "mouseover",
    "mouseup",
    "scroll",
    "select",
    "drag",
    "drop",
  ],
  Node: [
    "require",
    "module",
    "exports",
    "fs",
    "http",
    "events",
    "process",
    "path",
    "dirname",
    "basename",
    "join",
    "readFile",
    "readFileSync",
    "writeFile",
    "writeFileSync",
    "appendFile",
    "appendFileSync",
    "mkdir",
    "mkdirSync",
    "readdir",
    "rename",
    "renameSync",
    "rmdir",
    "rmdir",
    "rmdirSync",
    "createServer",
    "end",
    "req",
    "res",
    "port",
    "node",
  ],
};

const generateKeywords = (mode = "Vanilla Js") => {
  // generate a random array of keywords from the array of mode type
  let randomKeywords = [];

  for (let i = 0; i < 100; i++) {
    let randomIndex = Math.floor(Math.random() * keywords[mode].length);
    randomKeywords.push(keywords[mode][randomIndex]);
  }
  return randomKeywords;
};

export default generateKeywords;
